### ISSUE TITLE
文章打开就报错

### ISSUE THREAD

**Issue by Master-in** [Yue-plus/hexo-theme-arknights#100]
Unhandled rejection TypeError: 
 C:\Users\29621\Desktop\12\Hexo\themes\arknights\layout\post.pug:74
    72|       details#reward
     73|         summary #{__('post.reward')}
  > 74|         each imgSrc, pay in reward
    75|           div
    76|             span #{pay}
    77|             br

Cannot read properties of null (reading 'length')
    at eval (eval at wrap (C:\Users\29621\Desktop\12\Hexo\node_modules\_pug-runtime@3.0.1@pug-runtime\wrap.js:6:10), <anonymous>:628:32)
    at eval (eval at wrap (C:\Users\29621\Desktop\12\Hexo\node_modules\_pug-runtime@3.0.1@pug-runtime\wrap.js:6:10), <anonymous>:659:4)
    at template (eval at wrap (C:\Users\29621\Desktop\12\Hexo\node_modules\_pug-runtime@3.0.1@pug-runtime\wrap.js:6:10), <anonymous>:1143:7)
    at _View._compiled (C:\Users\29621\Desktop\12\Hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (C:\Users\29621\Desktop\12\Hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at C:\Users\29621\Desktop\12\Hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (C:\Users\29621\Desktop\12\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\29621\Desktop\12\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\29621\Desktop\12\Hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

怎么处理啊？

**Comment by ToUNVRSe** [comment]
将 `_config.arknights.yml` 中第 28 行设为 `false`

```JSON
reward: false
```

>< 我的锅

**Comment by Master-in** [comment]
感谢

**Comment by feilongproject** [comment]
解决问题后请主动关闭这个issue
