### ISSUE TITLE
未知的报错，但似乎不影响正常使用

### ISSUE THREAD

**Issue by SherkeyXD** [Yue-plus/hexo-theme-arknights#40]
ERROR {
  err: SyntaxError: Unexpected token / in JSON at position 29
      at JSON.parse (<anonymous>)
      at Hexo.jsonRenderer (E:\VSCodeFiles\SherkeyBlog\node_modules\hexo\lib\plugins\renderer\json.js:4:15)
      at Hexo.tryCatcher (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\method.js:15:34)
      at E:\VSCodeFiles\SherkeyBlog\node_modules\hexo\lib\hexo\render.js:81:22
      at tryCatcher (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\VSCodeFiles\SherkeyBlog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:464:21)
} Asset render failed: %s js/tsconfig.json

**Comment by Yue-plus** [comment]
请描述一下复现过程，并将版本号和 `package.json` 文件贴上来

这个问题 *可能* 是 node.js 依赖问题导致的，可以尝试删除 Hexo 目录下的 `node_modules` 文件夹并执行 `cnpm install` 重新安装依赖。

**Comment by SherkeyXD** [comment]
尝试了一下直接从头构建，仍会出现这个问题
npm version: 8.4.0
nodejs version: 16.13.1
package.json: 
> {
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.0.0"
  },
  "dependencies": {
    "hexo": "^6.0.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}

估计是node版本的锅

**Comment by Yue-plus** [comment]
> 



> 尝试了一下直接从头构建，仍会出现这个问题 npm version: 8.4.0 nodejs version: 16.13.1 package.json:
> 
> > {
> > "name": "hexo-site",
> > "version": "0.0.0",
> > "private": true,
> > "scripts": {
> > "build": "hexo generate",
> > "clean": "hexo clean",
> > "deploy": "hexo deploy",
> > "server": "hexo server"
> > },
> > "hexo": {
> > "version": "6.0.0"
> > },
> > "dependencies": {
> > "hexo": "^6.0.0",
> > "hexo-browsersync": "^0.3.0",
> > "hexo-generator-archive": "^1.0.0",
> > "hexo-generator-category": "^1.0.0",
> > "hexo-generator-index": "^2.0.0",
> > "hexo-generator-tag": "^1.0.0",
> > "hexo-renderer-ejs": "^2.0.0",
> > "hexo-renderer-marked": "^5.0.0",
> > "hexo-renderer-pug": "^3.0.0",
> > "hexo-renderer-stylus": "^2.0.0",
> > "hexo-server": "^3.0.0",
> > "hexo-theme-landscape": "^0.0.3"
> > }
> > }
> 
> 估计是node版本的锅

不是 node.js 的问题，我的版本是 `v16.13.2`

可能是 hexo 版本的问题，可以尝试使用 hexo 5.4.1 或等待主题更新（预计两到三天）

**Comment by Yue-plus** [comment]
主题 `1.14.0` 已发布，此报错已解决。

这是由于之前主题目录下的  `source\js\tsconfig.json` 文件中含有注释引起的，此报错并不影响使用，`1.14.0` 版本已删除此文件。
