### ISSUE TITLE
hexo g报错

### ISSUE THREAD

**Issue by SherkeyXD** [Yue-plus/hexo-theme-arknights#81]
ERROR {
  err: SyntaxError: Unexpected token ] in JSON at position 40
      at JSON.parse (<anonymous>)
      at Hexo.jsonRenderer (D:\Workplace\Blog\node_modules\hexo\lib\plugins\renderer\json.js:4:15)
      at Hexo.tryCatcher (D:\Workplace\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (D:\Workplace\Blog\node_modules\bluebird\js\release\method.js:15:34)
      at D:\Workplace\Blog\node_modules\hexo\lib\hexo\render.js:81:22
      at tryCatcher (D:\Workplace\Blog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Workplace\Blog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Workplace\Blog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Workplace\Blog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Workplace\Blog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\Workplace\Blog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\Workplace\Blog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\Workplace\Blog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\Workplace\Blog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:466:21)

**Comment by Yue-plus** [comment]
请切换到 1.15.1 试试？

```bash
git checkout 1.15.1
```

**Comment by SherkeyXD** [comment]
1.15.1没有这个问题
但是好像也不影响使用（
