### ISSUE TITLE
hexo生成问题，报错如下

### ISSUE THREAD

**Issue by EmberBurning** [Yue-plus/hexo-theme-arknights#96]
`ERROR
TypeError: D:\blog\Hexo\themes\arknights\layout\post.pug:4
    2|
    3| block content
  > 4|   -
    5|     const prev = page.prev
    6|     const next = page.next
    7|     const dateConf = theme.post.date

wordcount is not a function
    at eval (eval at wrap (D:\blog\Hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:457:52)
    at template (eval at wrap (D:\blog\Hexo\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1102:7)
    at _View._compiled (D:\blog\Hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\blog\Hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\blog\Hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\blog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\Hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

怎么处理？

**Comment by Yue-plus** [comment]
需要安装 [hexo-wordcount](https://github.com/willin/hexo-wordcount) 依赖。
不需要的话可以参考 [README.md#字数/阅读时长统计](https://github.com/Yue-plus/hexo-theme-arknights#%E5%AD%97%E6%95%B0%E9%98%85%E8%AF%BB%E6%97%B6%E9%95%BF%E7%BB%9F%E8%AE%A1) 关闭此功能。

**Comment by EmberBurning** [comment]
> 需要安装 [hexo-wordcount ](https://github.com/willin/hexo-wordcount) 依赖。 不需要的话可以参考 [README.md#字数/阅读时长统计 ](https://github.com/Yue-plus/hexo-theme-arknights#%E5%AD%97%E6%95%B0%E9%98%85%E8%AF%BB%E6%97%B6%E9%95%BF%E7%BB%9F%E8%AE%A1) 关闭此功能。

感谢
